### ISSUE TITLE
driver cannot authenticate in ActiveDirectoryPassword mode

### ISSUE THREAD

**Issue by yaitskov** [lurcher/unixODBC#123]
Hi,

I run Debian 10 and trying to connect to Sql Server deployed in Azure Cloud (I don't manage server).
I tried MS Sql ODBC driver versions 17.10 and 18.1. 
sqlcmd program, provided by Microsoft, using the same SO library, connects to the server.

```
  sqlcmd -G -S kit.database.windows.net,1433 -U daniil.iaitskov@xxx.onmicrosoft.com -P Abcdefg123- -d db1
```

but iusql and my program using following connection string fails:

```
iusql -v ';Server=tcp:kit.database.windows.net,1433;Initial Catalog=db1;Persist Security Info=No;UID=daniil.iaitskov@xxx.onmicrosoft.com;Pwd=Abcdefg123-;MultipleActiveResultSets=No;Encrypt=Yes;TrustServerCertificate=No;Connection Timeout=30;Authentication=ActiveDirectoryPassword;'

[Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Failed to authenticate the user 'daniil.iaitskov@xxx.onmicrosoft.com' in Active Directory (Authentication option is 'ActiveDirectoryPassword').
Error code 0xA190; state 41360
Error getting realm info

[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Could not load libcurl, make sure it is installed.
[Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Timeout error [258].
[Microsoft][ODBC Driver 17 for SQL Server]Unable to complete login process due to delay in login response
[ISQL]ERROR: Could not SQLDriverConnect

```

Is curl dependency requested after authentication error? Why?

**Comment by v-chojas** [comment]
AAD authentication methods need libcurl due to the API (OAuth) which is used for that.

Also it appears you have some invalid connection string keywords, https://learn.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute?view=sql-server-ver16 has the full list of valid ones.

**Comment by yaitskov** [comment]
Connection is string is generated by Azure. I had manually replace False/True with Yes/No and remove spaces in "Active Directory Password".

```
Server=tcp:kit.database.windows.net,1433;Initial Catalog=db1;Persist Security Info=False;User ID={your_username};Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Authentication="Active Directory Password";
```

**Comment by yaitskov** [comment]
Once I put libcurl to the location discovered by strace AD authentication got fixed.

**Comment by v-chojas** [comment]
That connection string looks like it is for .NET SqlClient, not ODBC. As you saw, some of the keywords are similar but different.

**Comment by yaitskov** [comment]
https://github.com/NixOS/nixpkgs/pull/197140
