### ISSUE TITLE
Connection pool identification in trace file

### ISSUE THREAD

**Issue by dertin** [lurcher/unixODBC#143]
Hello,

I can't find clear evidence from the trace file if the pool connections are being reused correctly.

The environment value remains consistently 0x7f3... for all connections, which is expected.

However, the value of Connection always changes in all instances of SQLDriverConnectW. 
I expect it to remain the same when the connection is reused.

It is not obvious if you are using the PoolMaxSize=15 and PoolWaitTimeout=30 parameters, how to check this?.

The trace file only shows a distinction when Pooling = No, 
where it prints the "Threading Level..." configuration parameters (although I'm not sure why):

```
[ODBC][100274][1689403145.680766][SQLDriverConnectW.c][298]
    ...
    Threading Level set from Driver Entry in ODBCINST.INI 99 from '99'

    Threading Level set from [ODBC] Section in ODBCINST.INI 0 from '0'

    CPTimeout set to 180 from '180'

    UNICODE Using encoding ASCII 'UTF8' and UNICODE 'UTF16LE'
```

Here is the installation process I followed, along with a question I have:

```sh
git clone https://github.com/lurcher/unixODBC.git unixodbc-master
cd unixodbc-master
# I'm using a single Environment shared between multiple threads safely.
# When I compile with this change:
# sed -i 's/\/\* #define SHARED_POOLED_ENV   1 \*\//\#define SHARED_POOLED_ENV   1 /' ./DriverManager/drivermanager.h
# Generates an error in the trace file: [ODBC][73302][1689401838.769638][SQLFreeHandle.c][239]Error: HY010
# However, a panic is not generated, the application does not lose the connection with the database. 
# What is the purpose of this flag?
autoreconf -fi
./configure --disable-gui --disable-drivers --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE
make
sudo make install
```

Here is the configuration of my drivers:

```console
cat /usr/local/etc/odbcinst.ini

[ODBC]
Trace=Yes
Trace File=/tmp/sql.log
Pooling=Yes
PoolMaxSize=15
PoolWaitTimeout=30

[ODBC_Driver_18_for_SQL_Server_Pool]
Description=Microsoft ODBC Driver 18 for SQL Server - POOL
Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.2.1
UsageCount=1
CPTimeout=180

[ODBC_Driver_18_for_SQL_Server]
Description=Microsoft ODBC Driver 18 for SQL Server
Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.2.1
UsageCount=1
CPTimeout=0
```

Is it possible to add more information to the trace file about what is happening in the connection pool? It would be very useful to have this information. Thank you.

**Comment by lurcher** [comment]
On 15/07/2023 08:14, Guillermo Céspedes Tabárez wrote:
>
> Hello,
>
> I can't find clear evidence from the trace file if the pool connections are being reused correctly.
>
> The environment value remains consistently 0x7f3... for all connections, which is expected.
>
> However, the value of Connection always changes in all instances of SQLDriverConnectW.
> I expect it to remain the same when the connection is reused.
You will get a new application side connection handle, that's allocated before the DM knows what connection you want to use, and thats only discovered at the point of connection, so you will always get a newly allocated connection handle.
>
> It is not obvious if you are using the PoolMaxSize=15 and PoolWaitTimeout=30 parameters, how to check this?.
At the moment there is no way, though it will be simple to add more logging to the code to do this.
>
> The trace file only shows a distinction when Pooling = No,
> where it prints the "Threading Level..." configuration parameters (although I'm not sure why):

Because it was useful to know, when I was debugging the SQLLIB problems. And I left them there.
> [ODBC][100274][1689403145.680766][SQLDriverConnectW.c][298]
>     ...
>     Threading Level set from Driver Entry in ODBCINST.INI 99 from '99'
>
>     Threading Level set from [ODBC] Section in ODBCINST.INI 0 from '0'
>
>     CPTimeout set to 180 from '180'
>
>     UNICODE Using encoding ASCII 'UTF8' and UNICODE 'UTF16LE'
>
> Here is the installation process I followed, along with a question I have:
> git clone https://github.com/lurcher/unixODBC.git unixodbc-master
> cd unixodbc-master
> # I'm using a single Environment shared between multiple threads safely.
> # When I compile with this change:
> # sed -i 's/\/\* #define SHARED_POOLED_ENV   1 \*\//\#define SHARED_POOLED_ENV   1 /' ./DriverManager/drivermanager.h
> # Generates an error in the trace file: [ODBC][73302][1689401838.769638][SQLFreeHandle.c][239]Error: HY010
> # However, a panic is not generated, the application does not lose the connection with the database. 
> # What is the purpose of this flag?
> autoreconf -fi
> ./configure --disable-gui --disable-drivers --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE
> make
> sudo make install

By default unixODBC will generate a new env handle each time SQLAllocEnv is called. That flag makes it generate a single env and then share that between connection. This is similar to the way a shared env is used on windows with pooling. I added the option to fix a problem in SQLLIB that was expecting the windows behavior. Having finally fixed that problem, I put the default back how it was (I don't like change for its own sake), with the option in the header to go the other way if someone knew what they wanted and could set it. After a bit of time and some use to convince me its stable it will probably be a config setting.

I will check whats going on with that error though.
>
> Here is the configuration of my drivers:
> cat /usr/local/etc/odbcinst.ini
>
> [ODBC]
> Trace=Yes
> Trace File=/tmp/sql.log
> Pooling=Yes
> PoolMaxSize=15
> PoolWaitTimeout=30
>
> [ODBC_Driver_18_for_SQL_Server_Pool]
> Description=Microsoft ODBC Driver 18 for SQL Server - POOL
> Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.2.1
> UsageCount=1
> CPTimeout=180
>
> [ODBC_Driver_18_for_SQL_Server]
> Description=Microsoft ODBC Driver 18 for SQL Server
> Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.2.1
> UsageCount=1
> CPTimeout=0
>
> Is it possible to add more information to the trace file about what is happening in the connection pool? It would be very useful to have this information. Thank you.
Yep, the code is there to add whatever you feel is helpful, and it may be worth adding to code base. I generally log whats going on from the application side, and the log is mainly used (like on windows) to see what the application is asking the DM to do, not the internal behavior of the DM. I normally check whats going on by turning on driver logging to see what thats being asked to do.

**Comment by dertin** [comment]
Hi, @lurcher 

I have added dm_log_write(...) inside search_for_pool(...) to analyze trace file messages and understand connection pool management.

- Creation of the first pool connection: [link](https://github.com/lurcher/unixODBC/blob/master/DriverManager/SQLConnect.c#L3711-L3733)
- Reuse connection from pool: [start here](https://github.com/lurcher/unixODBC/blob/master/DriverManager/SQLConnect.c#L3306)
- Issue with increasing active connections in the pool: I noticed it always reuses the same connection and never enters [here](https://github.com/lurcher/unixODBC/blob/master/DriverManager/SQLConnect.c#L3700-L3708) What have I not understood?

What am I doing wrong? How can I force it to enter that part of the code? I am sending a large number of connections on threads from my program, expecting all threads to be ready to connect at the same time, with a single shared environment among all threads.

**Comment by dertin** [comment]
> Issue with increasing active connections in the pool: I noticed it always reuses the same connection and never enters [here](https://github.com/lurcher/unixODBC/blob/master/DriverManager/SQLConnect.c#L3700-L3708) What have I not understood?

I made a change in my program to force certain behaviors, and now I have multiple active connections in the pool, which is what I needed to verify. The code of my program in rust:  [here](https://gist.github.com/dertin/d5e6b031cb86fbe71c6d2272c764dedd#file-test_odbc_pool_mssql-rs-L9-L15)

Next, I will test different Drivers running simultaneously in separate threads, each with its environment.

**Comment by dertin** [comment]
I keep getting this error with a SQL Server connection:

[ODBC][27952][1689635914.618278][SQLFreeHandle.c][239]Error: HY010
[ODBC][27952][1689635914.618305][SQLFreeHandle.c][239]Error: HY010

[sql.log](https://github.com/lurcher/unixODBC/files/12074694/sql.log)

Can you reproduce this ? @lurcher

**Comment by dertin** [comment]
@lurcher your last commit f6dc22c185c2ba960681301c3dc28a58a9e39077 fixed what I said in my last post. Thank you.
