### ISSUE TITLE
Release 2.3.12 is missing the binary

### ISSUE THREAD

**Issue by esetnik** [lurcher/unixODBC#144]
On github the previous release includes a tar archive [https://github.com/lurcher/unixODBC/releases/download/2.3.11/unixODBC-2.3.11.tar.gz](https://github.com/lurcher/unixODBC/releases/download/2.3.11/unixODBC-2.3.11.tar.gz). Is it intentional that it's missing from the 2.3.12 release?

**Comment by hughmcmaster** [comment]
All assets are available from the release page, including the source tar for 2.3.12.

**Comment by esetnik** [comment]
Interesting. When my CI run ran previously it was missing.
