### ISSUE TITLE
isql crashes with one space character on standard input

### ISSUE THREAD

**Issue by Jacob-Burckhardt** [lurcher/unixODBC#146]
Using bash, this command:

`printf " " | isql -b LIVE_Config -v`

produces this output:

`Segmentation fault (core dumped)`

It works if you remove the space in the printf command like this

`printf "" | isql -b LIVE_Config -v`

That command outputs nothing as expected.

/etc/odbc.ini says (password changed to protect confidentiality):

```
[LIVE_Config]
Driver       = MySQLdriver
SERVER       = 192.168.10.230
PORT         = 3306
USER         = tcsApplication
Password     = xxxxxx
Database     = LIVE_Config
```

/etc/odbcinst.ini says:

```
[MySQLdriver]
Driver       = /usr/lib64/libmyodbc5.so
```

It occurred on Amazon Linux 2 using rpm unixODBC-2.3.1-14.amzn2.x86_64.

**Comment by v-chojas** [comment]
unixODBC 2.3.1 is _very_ old, please see all the Bugfixes since then: https://www.unixodbc.org/

I don't have a MySQL but your test case worked fine for me with MS SQL Server , msodbcsql18 driver and unixODBC 2.3.11. Please try a newer unixODBC first.

**Comment by lurcher** [comment]
On 10/08/2023 20:44, v-chojas wrote:
>
> unixODBC 2.3.1 is /very/ old, please see all the Bugfixes since then: 
> https://www.unixodbc.org/
>
> I don't have a MySQL but your test case worked fine for me with MS SQL 
> Server , msodbcsql18 driver and unixODBC 2.3.11. Please try a newer 
> unixODBC first.
>
>
Yep, I tried it with the latest build, MySQL and SQL Server, both fine, 
also a much older build, also fine, though the older build passed the 
empty string to the driver which then reported a empty query.

If you want to use your version, I would check with a debugger just 
where the seg fault is happening. May be in the driver.

**Comment by Jacob-Burckhardt** [comment]
I don't have an easy way to quickly test a newer version, but I will trust your testing.  Sorry to take up your time; I should have checked to see how old my version was.

**Comment by lurcher** [comment]
On 10/08/2023 21:02, Jacob-Burckhardt wrote:
>
> I don't have an easy way to quickly test a newer version, but I will 
> trust your testing. Sorry to take up your time; I should have checked 
> to see how old my version was.
>
>
No problem, I would still check where the seg fault is happening, may be 
driver, worth knowing.
