### ISSUE TITLE
Connection pooling causes memory leak using IBM i Access driver

### ISSUE THREAD

**Issue by deliego** [lurcher/unixODBC#151]
**Environment**
**OS:** Ubuntu 20.04, 16.04
**Python:** 3.6.3, 3.8, 3.10
**pyodbc:** 5.0.1, 4.0.39
**unixODBC** 2.3.12, 2.3.11, 2.3.8
**Driver:** IBM i Access ODBC Driver (can be downloaded from [IBM's support site](https://www.ibm.com/support/pages/ibm-i-access-client-solutions))

**Issue:**
When Connection Pooling is enabled, connections to IBM i server are never re-used and they never timeout or expire. Each time it connects, it's a brand new connection. This starts consuming more memory and the number of open files keeps increasing until it maxes out, then crashes.

- This works fine when Connection Pooling is not enabled, but connection pooling is needed.
- Makes no difference using 32-bit or 64-bit driver.
- Makes no difference using Threading=0 or Threading=1
- Sleep interval in script is 10 seconds to speed up the leak.
- This works fine using Windows ODBC driver manager and same IBM i Access driver for Windows, so my guess is it could be either unixodbc or the driver on Linux perhaps?

---
**odbcinst.ini**:
```
[ODBC]
Trace=Yes
Trace File=/tmp/sql.log
Pooling=Yes

[IBM i Access ODBC Driver]
Description=IBM i Access for Linux ODBC Driver
Driver=/opt/ibm/iaccess/lib/libcwbodbc.so
Setup=/opt/ibm/iaccess/lib/libcwbodbcs.so
Driver64=/opt/ibm/iaccess/lib64/libcwbodbc.so
Setup64=/opt/ibm/iaccess/lib64/libcwbodbcs.so
Threading=1
DontDLClose=1
UsageCount=1
CPTimeout=60

[IBM i Access ODBC Driver 64-bit]
Description=IBM i Access for Linux 64-bit ODBC Driver
Driver=/opt/ibm/iaccess/lib64/libcwbodbc.so
Setup=/opt/ibm/iaccess/lib64/libcwbodbcs.so
Threading=1
DontDLClose=1
UsageCount=1
CPTimeout=60
```

**Test Python code**:
```
import pyodbc
import time

def query(host, user, password):
    print(f"Started")
    try:
        conn = pyodbc.connect("DRIVER={IBM i Access ODBC Driver};SYSTEM="+host+";UID="+user+";PWD={"+password+"};QueryTimeout=1;SQL_ATTR_QUERY_TIMEOUT=30")
        cursor = conn.cursor()

        cursor.execute("SELECT 100 AS VALUE FROM SYSIBM.SYSDUMMY1")
        row = cursor.fetchone()
        print(str(row))
        
    except pyodbc.Error as e:
        print(e)
    finally:
        cursor.close()
        conn.close()

    print("Ended")

def main():
    host = "<my_host>"
    user = "<my_user>"
    password = "<my_password>"

    while True:
        query(host, user, password)
        time.sleep(10)

if __name__ == '__main__':
    main()
```

**File handles open by PID**: lsof -p <pid>
[lsof_output.txt](https://github.com/lurcher/unixODBC/files/12908163/lsof_output.txt)

**SQL trace**: attached
[sql.log](https://github.com/lurcher/unixODBC/files/12908162/sql.log)

**Comment by lurcher** [comment]
On 15/10/2023 00:25, deliego wrote:
>
> *Environment*
> *OS:* Ubuntu 20.04, 16.04
> *Python:* 3.6.3, 3.8, 3.10
> *pyodbc:* 5.0.1, 4.0.39
> *Driver:* IBM i Access ODBC Driver (can be downloaded from IBM's 
> support site 
> <https://www.ibm.com/support/pages/ibm-i-access-client-solutions>)
>
I don't have a server I can connect to, so replicating is going to 
problematic. What version of unixODBC are you using? Can you build 
unixODBC on your test machine?

**Comment by deliego** [comment]
**unixODBC** 2.3.12, 2.3.11 and 2.3.8

Yeah might be hard without an IBM i system. If you, by any chance, have access to IBM's PDP or Techzone program, they will provision a test environment in a matter of minutes temporarily (IBM i, AIX, z/OS, RH, etc. you name it) for free.

Yeah I was able to build 2.3.12. Anything you would like me to test/do?

Thanks!

**Comment by lurcher** [comment]
On 16/10/2023 14:46, deliego wrote:
>
> *unixODBC* 2.3.12, 2.3.11 and 2.3.8
>
> Yeah might be hard without an IBM i system. If you, by any chance, 
> have access to IBM's PDP or Techzone program, they will provision a 
> test environment in a matter of minutes temporarily (IBM i, AIX, z/OS, 
> RH, etc. you name it) for free.
>
> Yeah I was able to build 2.3.12. Anything you would like me to test/do?
>
> Thanks!
>
Not sure yet, but it would be interesting to add some debug to see what 
the driver returns from the SQL_ATTR_CONNECTION_DEAD call.

My first step though is to try your python code with a driver here.

You could try the 2.3.13pre code (current in git, or tar on ftp server) 
and see if that's doing the same thing.

-- 

Nick

**Comment by deliego** [comment]
It still happens with 2.3.13pre.
This is going to sound dumb, but where exactly do I add debugging to output the value of SQL_ATTR_CONNECTION_DEAD? in SQLDisconnect.c? SQLGetConnectAttrW.c?
and how exactly?

**Comment by lurcher** [comment]
On 16/10/2023 18:56, deliego wrote:
>
> It still happens with 2.3.13pre.
> This is going to sound dumb, but where exactly do I add debugging to 
> output the value of SQL_ATTR_CONNECTION_DEAD? in SQLDisconnect.c? 
> SQLGetConnectAttrW.c?
> and how exactly?
>
Badly explained. Its in the code in SQLConnect.c in the function 
search_for_pool(). Thats where it runs through the list of connections 
looking for a matching one. If it find a match it then calls 
SQLGetConnectAttr in the driver to check the connection is available to 
reuse. but if its not it should remove that connection from the list.

I will add some debug to the code here and send you a copy to build and 
see if that helps us understand whats going on. Will try and get the 
Python working first when I have a moment.

**Comment by kadler** [comment]
I built unixODBC git and tested with the driver (driver dev here). On Ubuntu 20.04 w/ PyODBC 5.0.1 and Python 3.8 I was unable to replicate the issue. I added some debug statements and it all seems fine: SQL_ATTR_CONNECTION_DEAD returns SQL_CD_FALSE as expected. Testing against system unixODBC (2.3.6) doesn't seem to pool properly, though I don't know why due to lack of debug statements.

**Comment by v-chojas** [comment]
If I remember correctly there were plenty of little bugs with pooling on the earlier unixODBC versions, so I'm not surprised that it doesn't work on 2.3.6.

**Comment by deliego** [comment]
@kadler , you ran the same code with IBM i access driver, unixODBC >2.3.8, pyodbc 5.0.1 and it reuses connections in the pool?
Is the driver the same driver released back on 11/1/2022 in IBMiAccess_v1r1_LinuxAP?
Could you check your file pointers to see if they are increasing? and also process memory?
`lsof -p <pid>`

**Comment by kadler** [comment]
@deliego Yep, I reinstalled the driver from our apt repository just to make sure I have a clean install. After re-installing and setting CPTimeout back to 60, it is working just fine with git master.

**Comment by deliego** [comment]
Thanks for confirming. There has to be a difference.. I'm scratching my head here. May I ask, how are you confirming that it's working?
I'm going by memory, file descriptors, instances of database job connections I see on IBM i server. All three are increasing.
I don't have the SQL_ATTR_CONNECTION_DEAD debug value on mine yet, so not sure what that would return.

I confirmed I am on the latest driver version too: ibm-iaccess is already the newest version (1.1.0.27-1.0). Library files are also dated 11/1/2022
```
user1@ubuntu-20:~/$ python --version
Python 3.10.12
user1@ubuntu-20:~/$ odbcinst --version
unixODBC 2.3.13pre
```

**Comment by kadler** [comment]
@deliego I accidentally left this on over night. Checking htop shows basically no ram usage and lsof shows only a single TCP socket open. I also modified the script to fetch the `JOB_NAME` and that shows the same job every time, whereas on system unixODBC libraries it showed a different job name every time. I also modified the unixODBC code to add some debug to the pool code for adding/retrieving connections from the pool.

```
$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Ubuntu 20.04.6 LTS"

$ python --version
Python 3.8.10

$ odbcinst --version
unixODBC 2.3.13pre
```

SQL_ATTR_CONNECTION_DEAD is not a debug value, but a connection attribute that the driver manager calls to see if a connection in the pool is dead. It seems like ODBC trace doesn't dump this (probably because it's an internal thing, not something the application called), but if you enable driver tracing with `cwbtrc /dt:1`, you can find calls to retrieve the value (though it unfortunately doesn't show the value that was returned), eg.

```
2023-10-17;08:12:16.029;ODBC;143378;143378;10008;0x180: odbcapi.SQLGetConnectAttr Entry
2023-10-17;08:12:16.030;ODBC;143378;143378;10008;odbcattr.getConnectAttr Entry
2023-10-17;08:12:16.030;ODBC;143378;143378;10008;Attribute: 1209 (SQL_ATTR_CONNECTION_DEAD)
2023-10-17;08:12:16.030;ODBC;143378;143378;10008;odbcattr.getConnectAttr Exit rc=0
2023-10-17;08:12:16.030;ODBC;143378;143378;10008;0x180: odbcapi.SQLGetConnectAttr Exit rc=0
```

**Comment by lurcher** [comment]
On 17/10/2023 14:52, Kevin Adler wrote:
>
> @deliego <https://github.com/deliego> I accidentally left this on over 
> night. Checking htop shows basically no ram usage and lsof shows only 
> a single TCP socket open. I also modified the script to fetch the 
> |JOB_NAME| and that shows the same job every time, whereas on system 
> unixODBC libraries it showed a different job name every time. I also 
> modified the unixODBC code to add some debug to the pool code for 
> adding/retrieving connections from the pool.
>
> |$ grep PRETTY_NAME /etc/os-release PRETTY_NAME="Ubuntu 20.04.6 LTS" $ 
> python --version Python 3.8.10 $ odbcinst --version unixODBC 2.3.13pre |
>
> SQL_ATTR_CONNECTION_DEAD is not a debug value, but a connection 
> attribute that the driver manager calls to see if a connection in the 
> pool is dead. It seems like ODBC trace doesn't dump this (probably 
> because it's an internal thing, not something the application called), 
> but if you enable driver tracing with |cwbtrc /dt:1|, you can find 
> calls to retrieve the value (though it unfortunately doesn't show the 
> value that was returned), eg.
>
> |2023-10-17;08:12:16.029;ODBC;143378;143378;10008;0x180: 
> odbcapi.SQLGetConnectAttr Entry 
> 2023-10-17;08:12:16.030;ODBC;143378;143378;10008;odbcattr.getConnectAttr 
> Entry 2023-10-17;08:12:16.030;ODBC;143378;143378;10008;Attribute: 1209 
> (SQL_ATTR_CONNECTION_DEAD) 
> 2023-10-17;08:12:16.030;ODBC;143378;143378;10008;odbcattr.getConnectAttr 
> Exit rc=0 2023-10-17;08:12:16.030;ODBC;143378;143378;10008;0x180: 
> odbcapi.SQLGetConnectAttr Exit rc=0|

|Ahh, using that logging, do you see the driver having its connection 
disconnected at the end of its CPTimeout period?|

**Comment by kadler** [comment]
No, SQLDisconnect never gets called in the driver. Also from the sql.log, I see my debug statements indicating the SQLDisconnect from pyodbc put the connection back in the pool and the SQLDriverConnectW retrieving it from the pool:

```
[ODBC][143378][1697488278.666275][SQLDisconnect.c][307]
		Exit:[SQL_SUCCESS] (back to pool)
--
[ODBC][143378][1697488279.671013][SQLDriverConnectW.c][531]
		Exit:[SQL_SUCCESS] (from pool)
--
[ODBC][143378][1697488279.681640][SQLDisconnect.c][307]
		Exit:[SQL_SUCCESS] (back to pool)
--
[ODBC][143378][1697488280.684667][SQLDriverConnectW.c][531]
		Exit:[SQL_SUCCESS] (from pool)
```

**Comment by kadler** [comment]
@deliego Here's my steps:
```
git clone https://github.com/lurcher/unixODBC.git
cd unixODBC
./configure --sysconfdir=/etc
 make DESTDIR=$PWD/root install
sudo -e /etc/odbcinst.ini # Enable tracing and set CPTimeout
 python3 -m venv .venv
. .venv/bin/activate
pip install pyodbc
rm -f /tmp/sql.log && LD_LIBRARY_PATH=root/usr/local/lib python ~/gh-151.py
```

**Comment by deliego** [comment]
@kadler Thanks!. A lot of wrong turns, and lessons learned today. Your steps allowed me to debug it further, and all within a python venv so no system libraries were affecting my test (which was my issue).
Followed your steps, and I added debugging as well:
- It works in unixodbc-2.3.13pre
- It works in unixodbc-2.3.12
- It does not work in unixodbc-2.3.11 or previous versions, so whatever changes went into 2.3.12 👍.

Unfortunately, the whole package system on Ubuntu is a mess. Previous tests with 2.3.6 and 2.3.11 still had some references lingering around that I couldn't even find... There is no apt repository for ubuntu that has unixodbc-2.3.12, in fact, the most common build in those repositories is unixodbc-2.3.6 which is from 2019 up to 2.3.11 in some distributions. This is a problem obviously because installing basic packages or drivers tend to have a dependency on unixodbc but when it's built from source, it does not get registered or indexed for those package managers to know it was installed... so it tries to install whatever unixodbc version is the latest in the main repository.... 2.3.6, plus other old compatible libraries from that time.

The IBM i Access driver comes in rpm and debian packages and they have dependencies on libodbc1 odbcinst odbcinst1debian2 unixodbc and libstdc6+. Installing the driver automatically installs these dependencies (since they are not registered that they were previously installed) and these break unixodbc because it overwrites the one built from source with an old version from repository... as well as the libodbc* libraries.

I had to start clean with a new Linux instance, no trace of unixodbc or drivers or gcc installed previously.

- I built unixodbc-2.3.12 from source, default locations (--prefix=/usr --sysconfdir=/etc)
- I had to unpack the IBM i driver debian package:
`dpkg -x ibm-iaccess-1.1.0.27-1.0.amd64.deb ./tmp`
then extract the DEBIAN scripts
`dpkg -e ibm-iaccess-1.1.0.27-1.0.amd64.deb ./tmp`
then modify the control script and removed all dependencies
then repackage it
`dpkg-deb -b ./tmp ./built`
then install the driver
By default, the driver looks for odbcinst and libraries in /usr/local/bin and /usr/bin, so if you install unixodbc in a custom location, unixodbc registration will fail. In the debian control file is a PATH where it looks for unixodbc first, you might be able to change that and point to your custom location, but I didn't need to and didn't try it.

This worked, driver was installed and odbcinst registration was correct. Added my Pooling and CPTimeout to my /etc/odbcinst.ini. Started my app and it's not consuming memory anymore, connections are being reused from the pool.

I know a lot in this post was also about the IBM i driver, but could be useful for other people that might run into this. I was not sure if it was unixodbc or the driver.

@kadler , you might know this, is there a parameter we can pass to drive installer to skip installing dependencies?

Thank you so much!

**Comment by kadler** [comment]
@deliego The driver has no control over installation of dependencies as that's all handled by apt/dpkg. If there is such a thing, that'd be where to look. As an alternative to what you did, you could install to /usr/local instead (with --sysconfdir=/tmp to use the same configs as the system libraries) and then set LD_LIBRARY_PATH as appropriate for your application. Or you could build a new .deb and install that, which would prevent the system packages overwriting your custom build.

Having 2.3.6 in Ubuntu 20.04 is a bit annoying, but 22.04 has 2.3.9 and 23.10 will have 2.3.12. Presumably if 2.3.13 comes out within the next few months, 24.04 could pull it in before release.

**Comment by deliego** [comment]
Thanks for all your help.
