### ISSUE TITLE
Does MaxPoolSize limit the total number of connections that can be opened simultaneously?

### ISSUE THREAD

**Issue by mohsen-eng74** [lurcher/unixODBC#154]
Hello,
Does `MaxPoolSize` limit the total number of connections that can be opened simultaneously? I've configured the `/etc/odbcinst.ini` as follows, But whenever I create connections simultaneously (using asyncio or multithreading) the total number of opened connections (checked via `lsof -ai -p "PID"`) goes over the limit I've set for `MaxPoolSize` to the created number of threads or tasks.

```
[ODBC]
Pooling=1
UsageCount=2
MaxPoolSize=100
PoolWaitTimeout=30

[ODBC Driver 18 for SQL Server]
Description=Microsoft ODBC Driver 18 for SQL Server
Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.3.so.2.1
UsageCount=2
CPTimeout=120
```

Environment:
- Debian bookworm (12)
- Python 12
- PyODBC v5.0.1
- UnixODBC v2.3.11

Best Regards,
Mohsen

**Comment by lurcher** [comment]
On 16/12/2023 14:34, Mohsen Rahmati wrote:
>
> Hello,
> Does |MaxPoolSize| limit the total connection that can be opened 
> simultaneously? I've configured the |/etc/odbcinst.ini| as follows, 
> But whenever I create a connection simultaneously (using asyncio or 
> multithreading) the total number of opened connections (checked via 
> |lsof -ai -p "PID"|) goes over the limit I've set for |MaxPoolSize| to 
> the created number of threads or tasks.
>
No, it limits the number of connections that can be held in the pool 
waiting to be reused.

**Comment by mohsen-eng74** [comment]
> On 16/12/2023 14:34, Mohsen Rahmati wrote: Hello, Does |MaxPoolSize| limit the total connection that can be opened simultaneously? I've configured the |/etc/odbcinst.ini| as follows, But whenever I create a connection simultaneously (using asyncio or multithreading) the total number of opened connections (checked via |lsof -ai -p "PID"|) goes over the limit I've set for |MaxPoolSize| to the created number of threads or tasks.
> No, it limits the number of connections that can be held in the pool waiting to be reused.

Thanks.
Then, would you guide what the `Pool Wait_Timeout` parameter does?

**Comment by lurcher** [comment]
On 18/12/2023 03:25, Mohsen Rahmati wrote:
>
>     On 16/12/2023 14:34, Mohsen Rahmati wrote: Hello, Does
>     |MaxPoolSize| limit the total connection that can be opened
>     simultaneously? I've configured the |/etc/odbcinst.ini| as
>     follows, But whenever I create a connection simultaneously (using
>     asyncio or multithreading) the total number of opened connections
>     (checked via |lsof -ai -p "PID"|) goes over the limit I've set for
>     |MaxPoolSize| to the created number of threads or tasks.
>     No, it limits the number of connections that can be held in the
>     pool waiting to be reused.
>
> Thanks.
> Then, would you guide what the |Pool Wait_Timeout| parameter does?
>

The number of seconds a connection is left waiting in the pool list when 
inactive (not attached to an application).
