### ISSUE TITLE
64bit portability

### ISSUE THREAD

**Issue by jubalh** [lurcher/unixODBC#18]
rpmlint gives me the following error for unixODBC 2.3.7:

```
E: unixODBC 64bit-portability-issue SQLGetConnectAttr.c:393
E: unixODBC 64bit-portability-issue SQLGetConnectAttrW.c:337
```

They are both about the lines
```
*(SQLPOINTER**)value = sa->int_attr;
```

Maybe `uintptr_t` should be used?

**Comment by jubalh** [comment]
@lurcher, @v-chojas any opinions? :-)

**Comment by lurcher** [comment]
This has prompted me  to push a few small changes to tidy up some warnings. Hopefully its not broken anything, and hopefully it will help with this.

**Comment by jubalh** [comment]
Thank you @lurcher, this solved the issue.
For the record:
https://github.com/lurcher/unixODBC/commit/ca226e2e94f68ef7eee5ed9b6368f6550e3ecd56.patch
