### ISSUE TITLE
Please drop the internal libltdl library

### ISSUE THREAD

**Issue by hughmcmaster** [lurcher/unixODBC#48]
Why does unixODBC still ship libltdl? It seems very unnecessary these days.

Please consider dropping the internal libltdl library in favour of permanently using the system-installed version.

**Comment by lurcher** [comment]
On 07/12/2020 11:53, Hugh McMaster wrote:
>
> Why does unixODBC still ship libltdl? It seems very unnecessary these 
> days.
>
> Please consider dropping the internal libltdl library in favour of 
> permantently using the system-installed version.
>
>
My only concern (and I would welcome other views) is that its unixODBC 
and not linuxODBC so it has to handle platforms with non dlopen dynamic 
linking (hpux springs to mind).

-- 

Nick

**Comment by praiskup** [comment]
On Monday, December 7, 2020 1:00:26 PM CET Nick Gorham wrote:
> On 07/12/2020 11:53, Hugh McMaster wrote:
> >
> > Why does unixODBC still ship libltdl? It seems very unnecessary these 
> > days.
> >
> > Please consider dropping the internal libltdl library in favour of 
> > permantently using the system-installed version.
> >
> >
> My only concern (and I would welcome other views) is that its unixODBC 
> and not linuxODBC so it has to handle platforms with non dlopen dynamic 
> linking (hpux springs to mind).

The suggestion was not to drop libltdl use entirely, but to drop the use of
"bundled" internal libltdl (if I understood correctly).

Is it it possible to use system-default libltdl installed on hpux system?

E.g. unixODBC on Fedora is configured to use the default
/usr/lib64/libltdl.so.7.

Pavel

**Comment by jubalh** [comment]
> E.g. unixODBC on Fedora is configured to use the default

Same for openSUSE. We remove the local libltdl directory and use the system one.

**Comment by hughmcmaster** [comment]
> The suggestion was not to drop libltdl use entirely, but to drop the use of "bundled" internal libltdl (if I understood correctly).

Yes, I'm suggesting we drop the bundled version of libltdl, as it seems unnecessary to ship it.




> Same for openSUSE. We remove the local libltdl directory and use the system one.

In Debian, we just link with the system version.

**Comment by lurcher** [comment]
On 08/12/2020 12:34, Hugh McMaster wrote:
>
>     The suggestion was not to drop libltdl use entirely, but to drop
>     the use of "bundled" internal libltdl (if I understood correctly).
>
> Yes, I'm suggesting we drop the bundled version of libltdl, as it 
> seems unnecessary to ship it.
>
>     Same for openSUSE. We remove the local libltdl directory and use
>     the system one.
>
> In Debian, we just link with the system version.
>

As I say, my concern is for platforms I may not have available to test. 
What is the downside to shipping the bundled lib?

-- 
Nick

**Comment by jubalh** [comment]
> Yes, I'm suggesting we drop the bundled version of libltdl, as it seems unnecessary to ship it.

Why should it be dropped? If distributions can opt out that's all that is needed.

> What is the downside to shipping the bundled lib?

Nothing. I think it can just be left as is to make sure that it works on all systems. One could argue that a configure switch would be nice.

**Comment by lurcher** [comment]
On 08/12/2020 13:39, Michael Vetter wrote:
>
>     Yes, I'm suggesting we drop the bundled version of libltdl, as it
>     seems unnecessary to ship it.
>
> Why should it be dropped? If distributions can opt out that's all that 
> is needed.
>
>     What is the downside to shipping the bundled lib?
>
> Nothing. I think it can just be left as is to make sure that it works 
> on all systems. One could argue that a configure switch would be nice.
>

There is --with-included-ltdl

-- 
Nick

**Comment by jubalh** [comment]
Wasn't that on by default?

**Comment by lurcher** [comment]
On 08/12/2020 13:50, Michael Vetter wrote:
>
> Wasn't that on by default?
>
Yes. AFAIK.

-- 

Nick

**Comment by lurcher** [comment]
Ok, thanks for the clarification.
