### ISSUE TITLE
Makefile.in

### ISSUE THREAD

**Issue by polluks** [lurcher/unixODBC#70]
`config.status: error: cannot find input file: 'Makefile.in'`
What about Makefile.in? If you have a configure script, you should not call automake anymore IMHO.

**Comment by polluks** [comment]
We have Makefile.am but no Makefile.in, so you have to call automake explicit.

**Comment by lurcher** [comment]
Makefile.svn should get it as you need.On 26 Nov 2021 13:19, Stefan ***@***.***> wrote:
We have Makefile.am but no Makefile.in, so you have to call automake explicit.

**Comment by polluks** [comment]
Thanks, maybe you should mention Makefile.svn in the README.
