### ISSUE TITLE
clang & driver template

### ISSUE THREAD

**Issue by polluks** [lurcher/unixODBC#93]
clang wants prototypes:
````
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..  -I../../include -I. -I../../libltdl   -g -O2 -pthread -MT SQLAllocHandle.lo -MD -MP -MF .deps/SQLAllocHandle.Tpo -c -o SQLAllocHandle.lo SQLAllocHandle.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I../../include -I. -I../../libltdl -g -O2 -pthread -MT SQLAllocHandle.lo -MD -MP -MF .deps/SQLAllocHandle.Tpo -c SQLAllocHandle.c  -fno-common -DPIC -o .libs/SQLAllocHandle.o
SQLAllocHandle.c:23:10: error: implicit declaration of function '_AllocEnv' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                return _AllocEnv( (SQLHENV *)pnOutputHandle );
                       ^
````
[...]

**Comment by lurcher** [comment]
On 13/01/2022 20:15, Stefan wrote:
>
> clang wants prototypes:
>
> |/bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. 
> -I../.. -I../../include -I. -I../../libltdl -g -O2 -pthread -MT 
> SQLAllocHandle.lo -MD -MP -MF .deps/SQLAllocHandle.Tpo -c -o 
> SQLAllocHandle.lo SQLAllocHandle.c libtool: compile: gcc 
> -DHAVE_CONFIG_H -I. -I../.. -I../../include -I. -I../../libltdl -g -O2 
> -pthread -MT SQLAllocHandle.lo -MD -MP -MF .deps/SQLAllocHandle.Tpo -c 
> SQLAllocHandle.c -fno-common -DPIC -o .libs/SQLAllocHandle.o 
> SQLAllocHandle.c:23:10: error: implicit declaration of function 
> '_AllocEnv' is invalid in C99 
> [-Werror,-Wimplicit-function-declaration] return _AllocEnv( (SQLHENV 
> *)pnOutputHandle ); ^ |
>
Generally you should not be building the drivers by default, they are 
only there as samples and of historical interest.

**Comment by polluks** [comment]
I know what you mean. However a template is a starting point, gcc support still works and clang support works with #95.

**Comment by jubalh** [comment]
#95 needs to be cleaned up first.
